# Generated by Django 5.1.2 on 2024-10-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavolo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='event',
            new_name='event_key',
        ),
    ]
